name: pharmacy_app
description: A Flutter app to manage pharmacy medicines
publish_to: 'none' # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3 # Adjusted to the correct version of the HTTP package

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
