name: bmi_calculator
description: A professional modern BMI Calculator app

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2 # Add flutter_launcher_icons dependency
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"  # Specify the path for your app icon

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png  # The icon image path in the assets folder

